# Generated by Django 3.2.16 on 2025-06-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='annotation',
            field=models.TextField(blank=True, null=True, verbose_name='Annotation'),
        ),
    ]
