# Generated by Django 3.2.16 on 2025-06-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_lab', '0002_photo_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='annotation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Annotation'),
        ),
    ]
